forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib"

mod "mcollective",
    :git => "https://github.com/puppetlabs/puppetlabs-mcollective.git",
    :ref => "master"
mod "richardc/datacat"
mod "puppetlabs/java_ks"
mod "puppetlabs/activemq"

mod "razorsedge/vmwaretools"

mod "puppetlabs/puppetdb"
mod "puppetlabs/postgresql"
mod "puppetlabs/inifile"
mod "puppetlabs/concat"
