forge "http://forge.puppetlabs.com"

mod "vjanelle-puppet_config",
    :git => "https://github.com/vjanelle/vjanelle-puppet_config",
    :ref => "master"

mod "puppetlabs/stdlib"

mod "mcollective",
    :git => "https://github.com/puppetlabs/puppetlabs-mcollective.git",
    :ref => "master"
mod "richardc/datacat"
mod "puppetlabs/java_ks"
mod "puppetlabs/activemq"
mod "stahnma/epel"

mod "razorsedge/vmwaretools"

mod "puppetlabs/puppetdb"
mod "puppetlabs/postgresql", "3.1.0"
mod "puppetlabs/inifile"
mod "puppetlabs/concat"

# mcomaster

mod "maestrodev/rvm"

mod "dalen/puppetdbquery"
mod "dalen/dnsquery"

mod "hunner/haproxy_plugin"

mod "puppetlabs/haproxy"

mod "puppetlabs/apache"

mod "trlinkin/nsswitch"
mod 'trlinkin/validate_multi'
